# Generated by Django 5.1.7 on 2025-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackquestion',
            name='feedbackqn',
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='question_text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('rating', 'Rating')], default='text', max_length=20),
            preserve_default=False,
        ),
    ]
