# Generated by Django 5.1.7 on 2025-08-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedbackquestion_feedbackqn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='rating_answer',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='text_answer',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
